## This configuration was generated by terraform-provider-oci


resource oci_functions_function export_demo-api {
  depends_on     = [null_resource.demo-apiPush2OCIR]
  application_id = var.application_id
  config = {
  }
  defined_tags = {
  }
  display_name = "demo-api"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/demo-api:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_demo-keyval-load {
  depends_on     = [null_resource.demo-keyval-loadPush2OCIR]
  application_id = var.application_id
  config = {
  }
  defined_tags = {
  }
  display_name = "demo-keyval-load"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/demo-keyval-load:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_demo-load {
  depends_on     = [null_resource.demo-loadPush2OCIR]
  application_id = var.application_id
  config = {
  }
  defined_tags = {
  }
  display_name = "demo-load"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/demo-load:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "120"
  trace_config {
    is_enabled = "false"
  }
}

resource oci_functions_function export_load-target {
  depends_on     = [null_resource.load-targetPush2OCIR]
  application_id = var.application_id
  config = {
  }
  defined_tags = {
  }
  display_name = "load-target"
  freeform_tags = {
  }
  image              = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/load-target:0.0.1"
  memory_in_mbs      = "256"
  timeout_in_seconds = "300"
  trace_config {
    is_enabled = "false"
  }
}

