## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_Default_Group {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  description  = "The log group auto created for the users in selected comparmtent"
  display_name = "Default_Group"
  freeform_tags = {
  }
}

resource oci_logging_log export_nosql_demos_invoke {
  configuration {
    compartment_id = var.compartment_ocid
    source {
      category    = "invoke"
      resource    = oci_functions_application.export_nosql_demos_1.id
      service     = "functions"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
  }
  display_name = "nosql_demos_invoke"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_BaggageDemo_execution {
  configuration {
    compartment_id = var.compartment_ocid
    source {
      category    = "execution"
      resource    = oci_apigateway_deployment.export_BaggageDemo.id
      service     = "apigateway"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
  }
  display_name = "BaggageDemo_execution"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

resource oci_logging_log export_BaggageDemo_access {
  configuration {
    compartment_id = var.compartment_ocid
    source {
      category    = "access"
      resource    = oci_apigateway_deployment.export_BaggageDemo.id
      service     = "apigateway"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
  }
  display_name = "BaggageDemo_access"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_Default_Group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

